# GitHub Sponsors - Active
github: [Jaganpro]

# Ko-fi - Uncomment when you sign up at ko-fi.com
# ko_fi: your_kofi_username

# Buy Me a Coffee - Uncomment when you sign up at buymeacoffee.com
# custom: ["https://www.buymeacoffee.com/your_username"]
